# generated by Gemini: https://gemini.google.com/share/5d1aa7479826
# bundle.ps1
$inputFile = "main.cpp"
$outputFile = "main.cpp"

Write-Host "=== 汎用バンドル処理開始 ===" -ForegroundColor Green

if (-not (Test-Path $inputFile)) {
  Write-Host "Error: $inputFile が見つかりません。" -ForegroundColor Red
  exit
}

$content = Get-Content $inputFile -Raw

# 1. #ifdef LOCAL ～ #endif ブロックを抽出
$pattern = '(?s)#ifdef LOCAL(.*?)#endif'
$match = [regex]::Match($content, $pattern)

if ($match.Success) {
  Write-Host "LOCALブロックを検出しました。ライブラリを展開します..." -ForegroundColor Cyan
  
  $localBlock = $match.Groups[1].Value
  $expandedContent = $localBlock

  # 2. ブロック内の #include "..." をすべて抽出して置換
  # 抽出用正規表現: #include\s+"(.+?)"
  $includeMatches = [regex]::Matches($localBlock, '#include\s+"(.+?)"')

  foreach ($inc in $includeMatches) {
    $filePath = $inc.Groups[1].Value
    Write-Host "  -> 展開中: $filePath" -ForegroundColor Yellow
    
    if (Test-Path $filePath) {
      $libContent = Get-Content $filePath -Raw
      # インクルード文をファイル内容で置換
      $expandedContent = $expandedContent.Replace($inc.Value, $libContent)
    } else {
      Write-Host "  [!] Warning: $filePath が見つかりません。スキップします。" -ForegroundColor Red
    }
  }

  # 3. 元のソースの #ifdef LOCAL ブロック全体を、展開後の内容で差し替え
  $finalSource = $content.Replace($match.Value, $expandedContent)
    
  # 重複する pragma once などを削除したい場合はここで調整可能
  # $finalSource = $finalSource -replace '#pragma once', ''

  $finalSource | Set-Content $outputFile -Encoding UTF8
  Write-Host "`n✓ 完了: $outputFile を保存しました。" -ForegroundColor Green
} else {
  Write-Host "LOCALブロックが見つかりませんでした。置換せずにコピーします。" -ForegroundColor Yellow
  Copy-Item $inputFile $outputFile
}